name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.5.3
  - seaborn=0.12.2
  - pandas=1.5.2
  - pip=22.3.1
  - pandas-profiling=3.6.2
  - pyarrow=10.0.1
  - mlflow=2.0.1
  - pip:
      - wandb==0.13.9